### ISSUE TITLE
ValueError('Data passed to ks_2samp must not be empty')

### ISSUE THREAD

**Issue by veprbl** [eic/epic-capybara#9]
https://github.com/eic/EICrecon/actions/runs/6951726322/job/18914942243#step:11:127

**Comment by veprbl** [comment]
Resolved by #10

**Comment by wdconinc** [comment]
Not fixed.

**Comment by wdconinc** [comment]
https://github.com/eic/EICrecon/actions/runs/6974064668/job/18979747841?pr=1144#step:11:631

**Comment by wdconinc** [comment]
Can't reproduce locally... which is annoying.
